if(EXISTS "/home/runner/work/mini-rpc/mini-rpc/_codeql_build_dir/tests_tests-b12d07c.cmake")
  include("/home/runner/work/mini-rpc/mini-rpc/_codeql_build_dir/tests_tests-b12d07c.cmake")
else()
  add_test(tests_NOT_BUILT-b12d07c tests_NOT_BUILT-b12d07c)
endif()
